### ISSUE TITLE
Update for Self Hosting Idris2SH?

### ISSUE THREAD

**Issue by brittAnderson** [wchresta/idris2.nix#1]
Any hope of updating your derivation for the current instructions and repo for the installation of idris2 from here: https://github.com/edwinb/Idris2-SH ?

Would love to be able to do it myself on Nixos, but too new and having enough trouble just getting the regular things to work. If you have the time, other newcomers like myself would appreciate it.

**Comment by wchresta** [comment]
Is the request to create a derivation for `idris2boot` or update to the newest version of `idris2`?

I'll look into both with the goal to create a derivation for the newest idris2 version. I don't know if it would matter that the build happens with idris2-boot. I'm open to be convinced, though.

**Comment by brittAnderson** [comment]
I am imposing on your generosity so I don't want be demanding. While working through the type driven development book in idris I noticed that idris is being deprecated in favor of idris2. Seemed like it would be nice to try and use the new version, but I am also a nixos noob and don't feel confident to write the derviation. An update of your derivation to current idris2 would be appreciated, but going forward if idris2-boot is to be the future stand alone version then a derivation for that version might be more useful to more people in the community, eventually. Thanks for considering this request

**Comment by wchresta** [comment]
As far as I can tell, `idris2-boot` is only useful to compile the code in the `idris2` repository. Since there is a way to bootstrap without `idris2-boot` (by using scheme), it is not strictly necessary. I played around a bit, yesterday, and I couldn't get it to work with the scheme version. Probably there's a bug somewhere, but I'll try it tonight using `idris -> idris2-boot -> idris2` if I can't get the scheme version to work.

Meanwhile the best I can offer is the current derivation that gives you an old version of `idris2`. Maybe you'll be able to work through the first few chapters of the book until I figure out the derivation here.

**Comment by wchresta** [comment]
Alright, I think I got it to work. Edwin upgraded the scheme yesterday night which made the most obvious derivation compile.

Hope that helps; let me know if you run into any issues.

**Comment by brittAnderson** [comment]
Just confirming it works perfectly. Thanks.
